### ISSUE TITLE
ValueError: empty namespace prefix is not supported in ElementPath

### ISSUE THREAD

**Issue by namuyan** [flyte/upnpclient#9] opened 2017-12-21 03:07 UTC
Hello, I want to open port by UPnP.

```Python
import upnpclient
print(upnpclient.Device("http://192.168.1.1:8000/Public_UPNP_gatedesc.xml"))
```
I use softbank rooter.
I try to open port. but, xml error occur.

````python
Traceback (most recent call last):
  File "C:\Users\aaa\PycharmProjects\nem-chatto\test_upnp.py", line 7, in <module>
    devices = [upnpclient.Device("http://192.168.3.1:8000/Public_UPNP_gatedesc.xml")]
  File "C:\Users\aaa\Anaconda3\lib\site-packages\upnpclient\upnp.py", line 102, in __init__
    self.device_type = findtext('device/deviceType')
  File "src\lxml\lxml.etree.pyx", line 1550, in lxml.etree._Element.findtext (src\lxml\lxml.etree.c:58721)
  File "C:\Users\aaa\Anaconda3\lib\site-packages\lxml\_elementpath.py", line 306, in findtext
    el = find(elem, path, namespaces)
  File "C:\Users\aaa\Anaconda3\lib\site-packages\lxml\_elementpath.py", line 288, in find
    it = iterfind(elem, path, namespaces)
  File "C:\Users\aaa\Anaconda3\lib\site-packages\lxml\_elementpath.py", line 277, in iterfind
    selector = _build_path_iterator(path, namespaces)
  File "C:\Users\aaa\Anaconda3\lib\site-packages\lxml\_elementpath.py", line 234, in _build_path_iterator
    raise ValueError("empty namespace prefix is not supported in ElementPath")
ValueError: empty namespace prefix is not supported in ElementPath
````
I read error message. I check what make error.
I find `findtext() (lxml)` do not work correctly.
The error do not occur on Linux, only on Windows.
What is wrong?

**Comment by flyte** [comment] 2017-12-21 08:08
That's odd! Please could you provide the XML file involved? You should be able to get it from http://192.168.3.1:8000/Public_UPNP_gatedesc.xml

Make sure it doesn't contain any passwords etc before pasting it in. 

Cheers

**Comment by namuyan** [comment] 2017-12-25 12:37
```xml
<root>
    <specversion>
        <major>
            1
        </major>
        <minor>
            0
        </minor>
    </specversion>
    <urlbase>
        http://192.168.3.1:8000/
    </urlbase>
    <device>
        <devicetype>
            urn:schemas-upnp-org:device:InternetGatewayDevice:1
        </devicetype>
        <presentationurl>
            http://111.222.333.444/
        </presentationurl>
        <friendlyname>
            Residential Gateway
        </friendlyname>
        <manufacturer>
            Namyang Corp.
        </manufacturer>
        <manufacturerurl>
            http://namuyang.co.jp
        </manufacturerurl>
        <modeldescription>
            Residential Gateway
        </modeldescription>
        <modelname>
            Residential Gateway
        </modelname>
        <udn>
            uuid:123456-123456-123345
        </udn>
        <servicelist>
            <service>
                <servicetype>
                    urn:schemas-upnp-org:service:Layer3Forwarding:1
                </servicetype>
                <serviceid>
                    urn:upnp-org:serviceId:L3Forwarding1
                </serviceid>
                <scpdurl>
                    Public_UPNP_Layer3F.xml
                </scpdurl>
                <controlurl>
                    Public_UPNP_C1
                </controlurl>
                <eventsuburl>
                    Public_UPNP_Event_1
                </eventsuburl>
            </service>
        </servicelist>
        <devicelist>
        </devicelist>
    </device>
    <device>
        <devicetype>
            urn:schemas-upnp-org:device:WANDevice:1
        </devicetype>
        <friendlyname>
            WAN Device
        </friendlyname>
        <manufacturer>
            Namyang, Inc.
        </manufacturer>
        <manufacturerurl>
            http://namuyang.co.jp
        </manufacturerurl>
        <modeldescription>
            Residential Gateway
        </modeldescription>
        <modelname>
            Residential Gateway
        </modelname>
        <udn>
            uuid:11111111111-222222222222-333333
        </udn>
        <servicelist>
            <service>
                <servicetype>
                    urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1
                </servicetype>
                <serviceid>
                    urn:upnp-org:serviceId:WANCommonIFC1
                </serviceid>
                <scpdurl>
                    Public_UPNP_WAND.xml
                </scpdurl>
                <controlurl>
                    Public_UPNP_C2
                </controlurl>
                <eventsuburl>
                    Public_UPNP_Event_2
                </eventsuburl>
            </service>
        </servicelist>
        <devicelist>
        </devicelist>
    </device>
    <device>
        <devicetype>
            urn:schemas-upnp-org:device:WANConnectionDevice:1
        </devicetype>
        <friendlyname>
            WAN Connection Device
        </friendlyname>
        <manufacturer>
            Namyang, Inc.
        </manufacturer>
        <manufacturerurl>
            http://namuyang.co.jp
        </manufacturerurl>
        <modeldescription>
            Residential Gateway
        </modeldescription>
        <modelname>
            Residential Gateway
        </modelname>
        <udn>
            uuid:1111111111111-22222222222-33333333333
        </udn>
        <servicelist>
            <service>
                <servicetype>
                    urn:schemas-upnp-org:service:WANIPConnection:1
                </servicetype>
                <serviceid>
                    urn:upnp-org:serviceId:WANIPConn1
                </serviceid>
                <scpdurl>
                    Public_UPNP_WANIPConn.xml
                </scpdurl>
                <controlurl>
                    Public_UPNP_C3
                </controlurl>
                <eventsuburl>
                    Public_UPNP_Event_3
                </eventsuburl>
            </service>
            <service>
                <servicetype>
                    urn:schemas-upnp-org:service:WANPPPConnection:1
                </servicetype>
                <serviceid>
                    urn:upnp-org:serviceId:WANPPPConn1
                </serviceid>
                <scpdurl>
                    Public_UPNP_WANPPPConn.xml
                </scpdurl>
                <controlurl>
                    Public_UPNP_C5
                </controlurl>
                <eventsuburl>
                    Public_UPNP_Event_5
                </eventsuburl>
            </service>
        </servicelist>
    </device>
</root>
```
Thank you for comment, is this.

**Comment by flyte** [comment] 2018-01-30 15:30
The problem is because your device doesn't seem to include the right `xmlns` (or any at all, even). What we're expecting is something like `<root xmlns="urn:schemas-upnp-org:device-1-0">`.

As you can see in the uPnP specification, it "must" exist (page 44 of `UPnP-arch-DeviceArchitecture-v1.1.pdf` in the `doc` directory):
![screenshot from 2018-01-30 15-26-59](https://user-images.githubusercontent.com/1153496/35574634-3b236368-05d2-11e8-9d57-43fe1d6ead57.png)

I'll have to see what I can do about the missing namespace and see if it's feasible to work around.

**Comment by flyte** [comment] 2018-01-30 16:09
> The error do not occur on Linux, only on Windows.

Oh, I didn't spot this to begin with. This explains why I can't reproduce the issue!

**Comment by flyte** [comment] 2018-01-30 16:14
I'm sorry, but I can't find anything obvious about the differences between `lxml` on Linux and Windows. Perhaps try using a different (newer?) build and see if you still have the same issue. http://lxml.de/FAQ.html#where-are-the-binary-builds

I don't think I can help beyond this, so I'm going to close this issue. Hope you manage to get it working.

**Closed as completed by flyte** 2018-01-30 16:14 UTC
Labels: non-compliant device, windows
